import { Platform, StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from './colors';

export const createFindStyles = (width, normalize) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.white,
      paddingHorizontal: width * 0.04,
    },
    headerSection: {
      paddingTop: normalize(8),
      paddingHorizontal: width * 0.04,
      backgroundColor: 'transparent',
    },
    headerTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: normalize(30),
      position: 'relative',
    },
    backButton: {
      position: 'absolute',
      left: -normalize(4),
      padding: normalize(8),
    },
    headerTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.textLight4,
    },
    description: {
      marginTop: normalize(12),
      marginBottom: normalize(14),
      textAlign: 'center',
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.regular,
      color: colors.textLight4,
      lineHeight: normalize(22),
      paddingHorizontal: normalize(8),
    },
    contentSection: {
      flex: 1,
      paddingTop: normalize(8),
      paddingHorizontal: width * 0.04,
    },
    inputLabel: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textLight4,
      marginBottom: normalize(6),
      marginLeft: normalize(2),
    },
    inputWrapper: {
      width: '100%',
      alignItems: 'stretch',
      marginBottom: normalize(12),
    },
    input: {
      width: '100%',
      minHeight: normalize(52),
      borderWidth: 1.5,
      borderColor: colors.textLight2,
      borderRadius: normalize(16),
      paddingHorizontal: normalize(14),
      paddingVertical: normalize(12),
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.regular,
      color: colors.text,
      marginBottom: 0,
      backgroundColor: colors.white,
      textAlignVertical: 'center',
      ...Platform.select({
        android: { includeFontPadding: false, elevation: 0 },
        ios: {},
      }),
    },
    inputReadonly: {
      backgroundColor: colors.textLight5,
      color: colors.textLight4,
    },
    helperText: {
      marginTop: normalize(2),
      marginBottom: normalize(20),
      marginLeft: normalize(20),
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textLight4,
    },
    resultCard: {
      width: '98%',
      alignSelf: 'center',
      borderWidth: 1,
      borderColor: colors.primaryLight5,
      borderRadius: normalize(20),
      backgroundColor: colors.primaryLight2,
      paddingVertical: normalize(16),
      paddingHorizontal: normalize(16),
      marginTop: normalize(2),
      marginBottom: normalize(16),
    },
    resultTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.regular,
      color: colors.textLight4,
      marginBottom: normalize(6),
    },
    resultValue: {
      fontSize: normalize(fontSizes.title),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    footerSection: {
      paddingTop: normalize(8),
      paddingBottom: normalize(16),
      paddingHorizontal: width * 0.04,
      backgroundColor: 'transparent',
    },
    primaryButton: {
      width: '100%',
      backgroundColor: colors.primaryDark,
      borderRadius: normalize(24),
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: normalize(14),
    },
    primaryButtonDisabled: {
      backgroundColor: colors.textLight2,
    },
    primaryButtonText: {
      fontSize: normalize(fontSizes.xxl),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    inputWithButton: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '98%',
      marginBottom: normalize(12),
    },
    inputFlex: {
      flex: 1,
      marginBottom: 0,
      marginRight: normalize(8),
    },
    verifyButton: {
      paddingHorizontal: normalize(18),
      height: normalize(50),
      backgroundColor: colors.primaryDark,
      borderRadius: normalize(24),
      justifyContent: 'center',
      alignItems: 'center',
    },
    verifyButtonDisabled: {
      backgroundColor: colors.textLight2,
    },
    verifyButtonWide: {
      width: '100%',
      alignSelf: 'stretch',
      marginBottom: normalize(12),
      minHeight: normalize(52),
      borderRadius: normalize(16),
    },
    verifyButtonText: {
      fontSize: normalize(fontSizes.xxl),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    verifiedHint: {
      marginTop: normalize(4),
      marginBottom: normalize(12),
      marginLeft: normalize(20),
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.primaryDark,
    },
  });
};
