import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from './colors';

export const getNormalize = (width) => {
  const scale = width / 375;
  return (size) => Math.round(scale * size);
};

export const createFriendStyles = (normalize) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.white,
    },
    friendCountChip: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.primaryDark,
      backgroundColor: colors.primaryLight3,
      paddingHorizontal: normalize(10),
      paddingVertical: normalize(4),
      borderRadius: normalize(20),
    },
    requestsSection: {
      paddingVertical: normalize(12),
      paddingBottom: normalize(16),
      borderBottomWidth: 1,
      borderBottomColor: colors.textLight1,
    },
    requestsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: normalize(10),
    },
    requestsTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    requestsCount: {
      fontSize: normalize(fontSizes.lg),
      color: colors.primaryDark,
      marginLeft: normalize(6),
      fontFamily: fonts.bold,
    },
    requestsScroll: {
      paddingRight: normalize(24),
    },
    requestCard: {
      width: normalize(120),
      marginRight: normalize(12),
      alignItems: 'center',
      backgroundColor: colors.textLight1,
      borderRadius: normalize(12),
      paddingVertical: normalize(12),
      paddingHorizontal: normalize(8),
      borderWidth: 1,
      borderColor: colors.textLight1,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: normalize(2) },
      shadowOpacity: 0.08,
      shadowRadius: normalize(4),
      elevation: 2,
    },
    reqAvatar: {
      width: normalize(52),
      height: normalize(52),
      borderRadius: normalize(26),
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: normalize(8),
    },
    reqAvatarText: {
      fontSize: normalize(fontSizes.heading),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    reqName: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.text,
      marginBottom: normalize(2),
    },
    reqUsername: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.textLight4,
      marginBottom: normalize(10),
    },
    reqButtons: {
      flexDirection: 'row',
      gap: normalize(6),
    },
    reqAcceptBtn: {
      flex: 1,
      backgroundColor: colors.primary,
      paddingVertical: normalize(6),
      borderRadius: normalize(8),
      alignItems: 'center',
    },
    reqAcceptText: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    reqRejectBtn: {
      flex: 1,
      backgroundColor: colors.textLight1,
      paddingVertical: normalize(6),
      borderRadius: normalize(8),
      alignItems: 'center',
    },
    reqRejectText: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.textLight5,
    },
    searchWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: normalize(16),
      marginVertical: normalize(12),
      backgroundColor: colors.textLight1,
      borderRadius: normalize(12),
      paddingHorizontal: normalize(12),
      paddingVertical: normalize(10),
    },
    searchIcon: {
      marginRight: normalize(8),
    },
    searchInput: {
      flex: 1,
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.regular,
      color: colors.text,
      padding: 0,
    },
    listSectionTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.text,
      paddingTop: normalize(14),
      paddingBottom: normalize(8),
    },
    mainScroll: {
      flex: 1,
    },
    mainScrollContent: {
      paddingHorizontal: normalize(16),
      paddingBottom: normalize(40),
    },
    friendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: normalize(12),
    },
    avatar: {
      borderRadius: normalize(23),
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: normalize(12),
    },
    avatarText: {
      fontSize: normalize(fontSizes.title),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    friendInfo: {
      flex: 1,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(6),
      marginBottom: normalize(3),
    },
    friendName: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    friendUsername: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textLight4,
    },
    friendSchool: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textLight5,
    },
    friendIconBtn: {
      width: normalize(36),
      height: normalize(36),
      borderRadius: normalize(18),
      borderWidth: 1.5,
      borderColor: colors.alert,
      justifyContent: 'center',
      alignItems: 'center',
    },
    empty: {
      alignItems: 'center',
      marginTop: normalize(80),
      gap: normalize(12),
    },
    emptyText: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.regular,
      color: colors.textLight3,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.textLight3,
    },
    bottomSheet: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.white,
      borderTopLeftRadius: normalize(24),
      borderTopRightRadius: normalize(24),
      paddingHorizontal: normalize(24),
      paddingBottom: normalize(40),
      paddingTop: normalize(12),
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: normalize(4) },
      shadowOpacity: 0.12,
      shadowRadius: normalize(12),
      elevation: 10,
    },
    sheetHandle: {
      width: normalize(40),
      height: normalize(4),
      backgroundColor: colors.textLight1,
      borderRadius: normalize(2),
      alignSelf: 'center',
      marginBottom: normalize(20),
    },
    sheetFriendInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(14),
      marginBottom: normalize(16),
      marginTop: normalize(10),
    },
    sheetAvatar: {
      width: normalize(45),
      height: normalize(45),
      borderRadius: normalize(26),
      justifyContent: 'center',
      alignItems: 'center',
    },
    sheetAvatarText: {
      fontSize: normalize(22),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    sheetName: {
      fontSize: normalize(fontSizes.xxl),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    sheetNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(6),
    },
    sheetUsername: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textLight4,
    },
    sheetSchool: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textLight4,
    },
    sheetDivider: {
      height: 1,
      backgroundColor: colors.textLight1,
      marginBottom: normalize(16),
    },
    sheetAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: normalize(6),
      paddingVertical: normalize(14),
      backgroundColor: colors.textLight1,
      borderRadius: normalize(10),
      marginBottom: normalize(10),
    },
    sheetDeleteAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: normalize(6),
      paddingVertical: normalize(12),
      backgroundColor: colors.alertLight,
      borderRadius: normalize(10),
      marginBottom: normalize(10),
    },
    sheetBlockAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: normalize(6),
      paddingVertical: normalize(8),
      backgroundColor: colors.white,
      borderRadius: normalize(10),
      marginBottom: normalize(10),
    },
    sheetActionIcon: {
      borderRadius: normalize(22),
      justifyContent: 'center',
      alignItems: 'center',
      textAlign: 'center',
    },
    deleteActionIcon: {
      backgroundColor: colors.transparent,
    },
    blockActionIcon: {
      backgroundColor: colors.transparent,
    },
    sheetActionTitle: {
      fontSize: normalize(fontSizes.xxl),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    sheetDeleteActionTitle: {
      fontSize: normalize(fontSizes.xxl),
      fontFamily: fonts.bold,
      color: colors.alert,
    },
    sheetBlockActionTitle: {
      fontSize: normalize(fontSizes.xl + 1),
      fontFamily: fonts.regular,
      color: colors.textLight4,
    },
    deleteActionTitle: {
      color: colors.alert,
    },
    blockActionTitle: {
      color: colors.textLight4,
    },
    sheetActionSub: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textLight3,
    },
    sheetCancelBtn: {
      marginTop: normalize(16),
      paddingVertical: normalize(12),
      backgroundColor: colors.textLight1,
      borderRadius: normalize(20),
      alignItems: 'center',
    },
    sheetCancelText: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.textLight4,
    },
  });
