import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from './colors';

export const createServiceStyles = (normalize) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: normalize(20),
      paddingTop: normalize(16),
      paddingBottom: normalize(32),
      gap: normalize(8),
    },
    legalMetaBlock: {
      gap: normalize(4),
      marginBottom: normalize(4),
    },
    legalMetaLine: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
      lineHeight: normalize(20),
    },
    legalMetaLabel: {
      fontFamily: fonts.bold,
    },
    chapterTitle: {
      fontSize: normalize(fontSizes.xxl),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
      marginTop: normalize(8),
      marginBottom: normalize(2),
    },
    sectionTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
      marginTop: normalize(4),
      marginBottom: normalize(6),
    },
    para: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
      lineHeight: normalize(20),
    },
    bullet: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
      lineHeight: normalize(20),
      paddingLeft: normalize(4),
    },
    bulletNested: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
      lineHeight: normalize(20),
      paddingLeft: normalize(24),
    },
    divider: {
      height: 1,
      backgroundColor: colors.textLight10,
      marginVertical: normalize(6),
    },
    blockquote: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
      lineHeight: normalize(20),
      marginLeft: normalize(4),
      paddingLeft: normalize(12),
      borderLeftWidth: normalize(3),
      borderLeftColor: colors.textLight10,
      fontStyle: 'italic',
    },
    table: {
      width: '100%',
      alignSelf: 'stretch',
      borderWidth: 1,
      borderColor: colors.textLight10,
      borderRadius: normalize(8),
      marginVertical: normalize(4),
    },
    tableRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderBottomWidth: 1,
      borderBottomColor: colors.textLight10,
    },
    tableRowLast: {
      borderBottomWidth: 0,
    },
    tableHeaderRow: {
      backgroundColor: colors.textLight10,
    },
    tableCellLabel: {
      flexGrow: 2,
      flexShrink: 1,
      flexBasis: 0,
      minWidth: 0,
      paddingVertical: normalize(10),
      paddingHorizontal: normalize(10),
      borderRightWidth: 1,
      borderRightColor: colors.textLight10,
    },
    tableCellValue: {
      flexGrow: 3,
      flexShrink: 1,
      flexBasis: 0,
      minWidth: 0,
      paddingVertical: normalize(10),
      paddingHorizontal: normalize(10),
    },
    tableCellCol3Mid: {
      flexGrow: 3,
      flexShrink: 1,
      flexBasis: 0,
      minWidth: 0,
      paddingVertical: normalize(10),
      paddingHorizontal: normalize(10),
      borderRightWidth: 1,
      borderRightColor: colors.textLight10,
    },
    tableCellCol3Last: {
      flexGrow: 3,
      flexShrink: 1,
      flexBasis: 0,
      minWidth: 0,
      paddingVertical: normalize(10),
      paddingHorizontal: normalize(10),
    },
    tableCellCol3Label: {
      flexGrow: 2,
      flexShrink: 1,
      flexBasis: 0,
      minWidth: 0,
      paddingVertical: normalize(10),
      paddingHorizontal: normalize(10),
      borderRightWidth: 1,
      borderRightColor: colors.textLight10,
    },
    tableHeaderText: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
      lineHeight: normalize(20),
    },
    tableCellText: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
      lineHeight: normalize(20),
    },
    tableCellLabelText: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
      lineHeight: normalize(20),
    },
    tableCellContent: {
      minWidth: 0,
      flexShrink: 1,
    },
  });
