/** 전역 API 에러 코드 — 프론트·백·관리자 공통 문자열 */
export const API_ERROR_CODES = Object.freeze({
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  GRADUATED_BLOCKED: 'GRADUATED_BLOCKED',
  ADULT_BLOCKED: 'ADULT_BLOCKED',
  REVERIFICATION_RESTRICTED: 'REVERIFICATION_RESTRICTED',
});
