import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from './colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  friendCountChip: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.bold,
    color: colors.primaryDark,
    backgroundColor: colors.primaryLight20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  requestsSection: {
    paddingVertical: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.textLight10,
  },
  requestsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
    marginBottom: 10,
  },
  requestsTitle: {
    fontSize: fontSizes.xl,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
  },
  requestsCount: {
    fontSize: fontSizes.lg,
    color: colors.primaryDark,
    marginLeft: 6,
    fontFamily: fonts.bold,
  },
  requestsScroll: {
    paddingHorizontal: 0,
    paddingRight: 24,
  },
  requestCard: {
    width: 120,
    marginRight: 12,
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: colors.textLight10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  reqAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  reqAvatarText: {
    fontSize: fontSizes.heading,
    fontFamily: fonts.bold,
    color: colors.textWhite,
  },
  reqName: {
    fontSize: fontSizes.xl,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
    marginBottom: 2,
  },
  reqUsername: {
    fontSize: fontSizes.md,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  reqButtons: {
    flexDirection: 'row',
    gap: 6,
  },
  reqAcceptBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  reqAcceptText: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.bold,
    color: colors.textWhite,
  },
  reqRejectBtn: {
    flex: 1,
    backgroundColor: colors.disabled,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  reqRejectText: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.bold,
    color: colors.textLight70,
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginVertical: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: fontSizes.xl,
    fontFamily: fonts.regular,
    color: colors.textPrimary,
    padding: 0,
  },
  listSectionTitle: {
    fontSize: fontSizes.xl,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
    paddingHorizontal: 0,
    paddingTop: 14,
    paddingBottom: 8,
  },
  mainScroll: {
    flex: 1,
  },
  mainScrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  friendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.textLight5,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    fontSize: fontSizes.title,
    fontFamily: fonts.bold,
    color: colors.textWhite,
  },
  friendInfo: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  friendName: {
    fontSize: fontSizes.xl,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
  },
  friendUsername: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
  },
  friendSchool: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.regular,
    color: colors.textLight70,
  },
  friendIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: colors.alert,
    justifyContent: 'center',
    alignItems: 'center',
  },
  empty: {
    alignItems: 'center',
    marginTop: 80,
    gap: 12,
  },
  emptyText: {
    fontSize: fontSizes.xl,
    fontFamily: fonts.regular,
    color: colors.textLight40,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlayLight,
  },
  bottomSheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
    paddingTop: 12,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: colors.border,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetFriendInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 20,
  },
  sheetAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sheetAvatarText: {
    fontSize: 22,
    fontFamily: fonts.bold,
    color: colors.textWhite,
  },
  sheetName: {
    fontSize: fontSizes.xxl,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
    marginBottom: 2,
  },
  sheetUsername: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  sheetSchool: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.regular,
    color: colors.textLight40,
  },
  sheetDivider: {
    height: 1,
    backgroundColor: colors.textLight10,
    marginBottom: 16,
  },
  sheetAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 12,
  },
  sheetActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteActionIcon: {
    backgroundColor: colors.red,
  },
  blockActionIcon: {
    backgroundColor: colors.disabled,
  },
  sheetActionTitle: {
    fontSize: fontSizes.xl,
    fontFamily: fonts.bold,
    marginBottom: 2,
    color: colors.textPrimary,
  },
  deleteActionTitle: {
    color: colors.alert,
  },
  blockActionTitle: {
    color: colors.textLight70,
  },
  sheetActionSub: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.regular,
    color: colors.textLight40,
  },
  sheetCancelBtn: {
    marginTop: 16,
    paddingVertical: 14,
    backgroundColor: colors.surface,
    borderRadius: 14,
    alignItems: 'center',
  },
  sheetCancelText: {
    fontSize: fontSizes.xl,
    fontFamily: fonts.bold,
    color: colors.textSecondary,
  },
});

export default styles;
