import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from './colors';

// 다른 학교 화면 전용 스타일 (우리 학교 화면과 동일한 레이아웃)
export const createOtherSchoolStyles = (normalize) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      padding: normalize(16),
      paddingBottom: normalize(16),
    },
    schoolCardBlock: {
      marginBottom: normalize(12),
    },
    schoolCard: {
      alignSelf: 'stretch',
      flexDirection: 'column',
      justifyContent: 'center',
      backgroundColor: colors.background,
      borderRadius: normalize(16),
      padding: normalize(16),
      borderWidth: 2,
      borderColor: colors.primary,
    },
    schoolNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: normalize(8),
      marginBottom: normalize(6),
      marginTop: normalize(6),
    },
    schoolName: {
      fontSize: normalize(fontSizes.title),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    locationText: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
      marginLeft: normalize(4),
    },
    schoolInfoDivider: {
      alignSelf: 'stretch',
      backgroundColor: colors.textLight10,
      marginTop: normalize(15),
      marginBottom: normalize(15),
      height: 1,
    },
    statsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      gap: normalize(10),
    },
    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statValueContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(4),
    },
    statValue: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
    },
    mealCardBlock: {
      marginBottom: normalize(12),
    },
    mealSectionCard: {
      backgroundColor: colors.background,
      borderRadius: normalize(16),
      paddingHorizontal: normalize(10),
      paddingVertical: normalize(10),
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
      elevation: 3,
    },
    mealSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: normalize(8),
      paddingHorizontal: normalize(4),
    },
    mealSectionTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
      paddingLeft: normalize(4),
    },
    mealSectionMore: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
      paddingRight: normalize(4),
    },
    mealCard: {
      alignSelf: 'stretch',
      flexDirection: 'column',
      justifyContent: 'space-between',
      backgroundColor: colors.primaryLight20,
      borderRadius: normalize(16),
      padding: normalize(12),
    },
    mealSlotsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: normalize(8),
    },
    mealSlot: {
      flex: 1,
      paddingHorizontal: normalize(6),
    },
    mealSlotLast: {},
    mealSlotHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: normalize(4),
    },
    mealSlotTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(4),
    },
    mealSlotTitle: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
    },
    mealSlotBadge: {
      paddingHorizontal: normalize(5),
      paddingVertical: normalize(2),
      borderRadius: normalize(10),
      backgroundColor: colors.primaryLight30,
    },
    mealSlotBadgeText: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.primaryDark,
    },
    mealSlotMenus: {
      minHeight: normalize(80),
      justifyContent: 'flex-start',
    },
    mealSlotMenuText: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
      marginBottom: normalize(2),
    },
    mealSlotEmptyText: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
    },
    mealCardTop: {
      flexDirection: 'column',
      paddingBottom: normalize(10),
    },
    mealTypeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(6),
    },
    mealLabel: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
      marginBottom: normalize(2),
    },
    mealType: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
    },
    mealItemsWrap: {
      flexDirection: 'column',
    },
    mealItem: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textPrimary,
    },
    mealMore: {
      fontSize: normalize(fontSizes.md),
      fontFamily: fonts.regular,
      color: colors.primaryDark,
      textAlign: 'right',
    },
    grassCard: {
      borderRadius: normalize(16),
      paddingHorizontal: normalize(10),
      paddingVertical: normalize(10),
      marginBottom: normalize(12),
      backgroundColor: colors.background,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
      elevation: 3,
    },
    grassCardTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
      marginBottom: normalize(4),
      paddingLeft: normalize(4),
    },
    mailboxWideBlock: {
      alignSelf: 'stretch',
      marginBottom: normalize(12),
    },
    mailboxWideButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      alignSelf: 'stretch',
      backgroundColor: colors.background,
      borderRadius: normalize(16),
      paddingVertical: normalize(8),
      paddingHorizontal: normalize(15),
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryLight30,
    },
    mailboxWideIconWrap: {
      width: normalize(48),
      height: normalize(48),
      borderRadius: normalize(14),
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: normalize(14),
    },
    mailboxWideTextCol: {
      flex: 1,
      minWidth: 0,
      minHeight: normalize(48),
      justifyContent: 'center',
    },
    mailboxWideTitle: {
      fontSize: normalize(fontSizes.xl),
      fontFamily: fonts.bold,
      color: colors.textPrimary,
      includeFontPadding: false,
    },
    mailboxWideChevronWrap: {
      width: normalize(40),
      height: normalize(48),
      marginLeft: normalize(8),
      alignItems: 'center',
      justifyContent: 'center',
    },
    mailboxWideSubtitle: {
      fontSize: normalize(fontSizes.lg),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
    },
  });
};

